---
# just setup initial seed job
jobs:
  # setup IT dept special folder
  - script: >
      folder('it') {
        displayName('VBC IT')
        description('all things VBC IT')
        authorization {
            permissionAll('role.it.backoffice')
            permissionAll('role.it.backoffice.admin')
        }

        // prime with credentials store setup
        properties {
            folderCredentialsProperty {
                domainCredentials {
                }
            }
        }
      }

  # seed job for all job discovery
  - script: >
      pipelineJob('it/seed') {
        displayName('CICD seed')
        concurrentBuild(false)

        definition {
          cpsScm {
            // If selected, try to obtain the Pipeline script contents
            // directly from the SCM without performing a full checkout.
            lightweight(true)
            scm {
              git {
                // Specify the branches to examine for changes and to build.
                //FIXME make this configurable
                branch("${SEED_JOB_BRANCH}")
                remote {
                  credentials("${SEED_JOB_CREDENTIALS_ID}")
                  url("${SEED_JOB_REPO_URL}")
                }
              }
            }
            scriptPath("Jenkinsfile")
          }
        }
      }
...
